config/routes.rb
AutoTest::Application.routes.draw do
  resources :plan_types

  devise_for :users

  resources :test_plan_cases

  resources :test_plans

  resources :users

  resources :flow_date_types

  resources :flow_types

  resources :test_case_flows

  resources :test_cases 

  match 'home/index' => 'test_plan_cases#index'
  
  get '/test_plan_case/get_data' => "test_plan_cases#get_data"
  post '/test_plan_case/set_data' => "test_plan_cases#set_data"

  get '/test_cases/:id/pro' => "test_cases#pro", :as => "pro_test_cases"

  get '/test_cases/:id/excuse' => "test_cases#excuse", :as => "excuse_test_cases"

  get '/test_plans/:id/excuse' => "test_plans#excuse", :as => "excuse_test_plan"

  get '/test_plans/:id/pause' => "test_plans#pause", :as => "pause_test_plan"

  get '/test_plans/:id/stop' => "test_plans#stop", :as => "stop_test_plan"

  get '/test_plans/:id/resume' => "test_plans#resume", :as => "resume_test_plan"

  get '/test_plans/:id/result' => "test_plans#result", :as => "result_test_plan"

  get '/test_plans/:id/pro' => "test_plans#pro", :as => "pro_test_plan"

  get '/test_plans/:id/script' => "test_plans#script", :as => "script_test_plan"

  root :to => 'test_cases#index'

  

end

app/controllers/test_plan_cases_controller.rb
class TestPlanCasesController < ApplicationController
  
  # GET /test_plan_cases
  # GET /test_plan_cases.json
  def index
    @test_plan_cases = TestPlanCase.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @test_plan_cases }
    end
  end

  # GET /test_plan_cases/1
  # GET /test_plan_cases/1.json
  def show
    @test_plan_case = TestPlanCase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @test_plan_case }
    end
  end

  # GET /test_plan_cases/new
  # GET /test_plan_cases/new.json
  def new
     @test_plan = TestPlan.find(params[:test_plan_id])
    @test_plan_case = TestPlanCase.new
    @test_plan_case.test_plan_id = params[:test_plan_id]
    @test_cases = TestCase.all

    @test_cases.each do|test_case|
       test_plan_cases = TestPlanCase.where("test_case_id = ? and test_plan_id = ? ", test_case.id,params[:test_plan_id])
      if test_plan_cases.length > 0
        test_case.selected = true
      end

    end


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @test_plan_case }
    end
  end

  # GET /test_plan_cases/1/edit
  def edit
    @test_plan_case = TestPlanCase.find(params[:id])
  end

  # POST /test_plan_cases
  # POST /test_plan_cases.json
  def create
    @test_plan_case = TestPlanCase.new(params[:test_plan_case])

    respond_to do |format|
      if @test_plan_case.save
        format.html { redirect_to @test_plan_case, notice: 'Test plan case was successfully created.' }
        format.json { render json: @test_plan_case, status: :created, location: @test_plan_case }
      else
        format.html { render action: "new" }
        format.json { render json: @test_plan_case.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /test_plan_cases/1
  # PUT /test_plan_cases/1.json
  def update
    @test_plan_case = TestPlanCase.find(params[:id])

    respond_to do |format|
      if @test_plan_case.update_attributes(params[:test_plan_case])
        format.html { redirect_to @test_plan_case, notice: 'Test plan case was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @test_plan_case.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_plan_cases/1
  # DELETE /test_plan_cases/1.json
  def destroy
    @test_plan_cases = TestPlanCase.where("test_case_id = ? and test_plan_id = ? ", params[:test_plan_case][:test_case_id],params[:test_plan_case][:test_plan_id])
    
    @test_plan_cases.each do |test_plan_case|
      test_plan_case.destroy
    end



    respond_to do |format|
      format.html { redirect_to test_plan_cases_url }
      format.json { render json: @test_plan_case, status: :created, location: @test_plan_case }
      format.json { head :no_content }
    end
  end



  def get_data

    @test_case = TestCase.find(params[:test_case_id])
    respond_to do |format|
        format.js { render :layout => false }
    end
  end


  def set_data
    testdatas = TestPlanData.where("test_case_flow_id = ? and test_plan_id = ? ",
        params[:test_plan_data][:test_case_flow_id],params[:test_plan_data][:test_plan_id])

    testdatas.each do|data|
      data.destroy

    end

    @test_plan_data = TestPlanData.new(params[:test_plan_data])
    @test_plan_data.save
    respond_to do |format|
        format.js { render :layout => false }
    end
  end

end

app/helpers/test_plan_cases_helper.rb
module TestPlanCasesHelper
end

app/views/test_plan_cases/_form.html.erb
<%= form_for(@test_plan_case) do |f| %>
  <% if @test_plan_case.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_plan_case.errors.count, "error") %> prohibited this test_plan_case from being saved:</h2>

      <ul>
      <% @test_plan_case.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :test_case_id %><br />
    <%= f.text_field :test_case_id %>
  </div>
  <div class="field">
    <%= f.label :test_plan_id %><br />
    <%= f.text_field :test_plan_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_plan_cases/_get_data.erb
<p>
  <b>用例名:</b>
  <%= @test_case.title %>
</p>


<table border="1">
  <tr>
    <th>步骤</th>
    <th>动作类型</th>
    <th>元素定位</th>
    <th>数据类型</th>
    <th>数据</th>
  </tr>

  
    <% @test_case.test_case_flows.each do |test_case_flow| %>
    <tr>
    <td><%= test_case_flow.flow_seq %></td>
    <td><%= test_case_flow.flow_type.name %></td>
    <td><%= test_case_flow.flow_location %></td>
    <td>
      <select id="test_case_flow_flow_date_type_id_<%=test_case_flow.id%>" >
          <%FlowDateType.find(:all).each do |t|%>
           <option value="<%=t.id%>" 

             <%if  test_case_flow.get_test_data_by_plan(params[:test_plan_id])!=nil %>

              <%if t.id.to_s ==test_case_flow.get_test_data_by_plan(params[:test_plan_id]).flow_date_type_id.to_s %>
            selected="selected"
            <%end%>

             <%else%>
              <%if t.id == test_case_flow.flow_date_type_id %>
            selected="selected"
            <%end%>
             <%end%>
           

            ><%=t.name%></option>
          <%end%>
      </select>
    <td>

      <%if test_case_flow.flow_date!='' and test_case_flow.get_test_data_by_plan(params[:test_plan_id])==nil %>
      <input value="<%= test_case_flow.flow_date %>" class="test_data_class" test_flow_id="<%= test_case_flow.id %>"> 
      <%end%>

      <%if test_case_flow.get_test_data_by_plan(params[:test_plan_id]) !=nil %>
      <input value="<%= test_case_flow.get_test_data_by_plan(params[:test_plan_id]).test_data %>" class="test_data_class" test_flow_id="<%= test_case_flow.id %>"> 
      <%end%>

    </td>
     </tr>
    <% end %>
  

</table>
  <%= link_to '完成', "javascript:void(0)",:id=>"set_data" %>
<script type="text/javascript">
$("#set_data").bind("click",function(){

$(".test_data_class").each(function(){

  $.ajax({
             type: "POST",
             url: "/test_plan_case/set_data",
             data: {"test_plan_data[test_plan_id]":"<%=params[:test_plan_id]%>","test_plan_data[test_case_flow_id]": $(this).attr("test_flow_id"),"test_plan_data[test_data]": $(this).val(),"test_plan_data[flow_date_type_id]":$("#test_case_flow_flow_date_type_id_" + $(this).attr("test_flow_id")).val()},
             dataType: "json",
             success: function(data){
                
                      }
         });

})



})

  </script>

app/views/test_plan_cases/edit.html.erb
<h1>Editing test_plan_case</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_plan_case %> |
<%= link_to 'Back', test_plan_cases_path %>

app/views/test_plan_cases/get_data.js.erb
 $('#test_data').html('<%= escape_javascript(render :partial => 'get_data') %>');

app/views/test_plan_cases/index.html.erb
<h1>Listing test_plan_cases</h1>

<table>
  <tr>
    <th>Test case</th>
    <th>Test plan</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @test_plan_cases.each do |test_plan_case| %>
  <tr>
    <td><%= test_plan_case.test_case_id %></td>
    <td><%= test_plan_case.test_plan_id %></td>
    <td><%= link_to 'Show', test_plan_case %></td>
    <td><%= link_to 'Edit', edit_test_plan_case_path(test_plan_case) %></td>
    <td><%= link_to 'Destroy', test_plan_case, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Test plan case', new_test_plan_case_path %>

app/views/test_plan_cases/new.html.erb
<h1>新增测试计划-勾选测试用例</h1>

<p id="notice"><%= notice %></p>

<div>
<p>
  <b>测试计划:</b>
  <%= @test_plan.name %>
</p>
<p>
  <b>服务器:</b>
  <%= @test_plan.host %>
</p>

<p>
  <b>服务器用户名:</b>
  <%= @test_plan.user_name %>
</p>
<p>
  <b>日志路径:</b>
  <%= @test_plan.log_path %>
</p>
<p>--------------------------------------------------华丽的风格线----------------------------------------------------------</p>
</div>

<div id="center" style="">
<div style="float:left">
<table>
 <tr>
    <th>选择用例</th>
    <th>用例名称</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @test_cases.each do |test_case| %>
  <tr>
  	<td><input type="checkbox" class="checkbox_test_case" id="<%=test_case.id%>"  <%if test_case.selected %>checked=checked<%end%>> </td>
    <td><%= test_case.title %>
    <td><%= link_to '查看用例', test_case,:target=>"_blank" %></td>
    <td><%= link_to '执行脚本', excuse_test_cases_path(test_case) %></td>
     <td><%= link_to '添加脚本数据', "/test_plan_case/get_data?test_case_id=#{test_case.id}&test_plan_id=#{@test_plan.id}",:class=>"add_data",:remote => true%></td>
  </tr>
<% end %>
</table>
</div>
<div style="float:left;margin-left:50px;height:<%= @test_cases.length*25%>px; width:1px; border-left:2px #000 solid"></div>
<div style="float:left;margin-left:50px; width:60%" id="test_data"></div>
</div>

<div style="clear:both;"></div>
<div >
<p>-----------------------------------------------华丽的风格线------------------------------------------------------------</p>
<%= link_to '完成', test_plans_path %>
</div>
<script>
$(".checkbox_test_case").click(function(){

	 if ($(this).is(":checked")) {
         



	 		 $.ajax({
             type: "POST",
             url: "/test_plan_cases",
             data: {"test_plan_case[test_case_id]":$(this).attr("id"), "test_plan_case[test_plan_id]":"<%=@test_plan.id%>"},
             dataType: "json",
             success: function(data){
             		
                      }
         });
        }else{
        	$.ajax({
             type: "DELETE",
             url: "/test_plan_cases/1",
             data: {"test_plan_case[test_case_id]":$(this).attr("id"), "test_plan_case[test_plan_id]":"<%=@test_plan.id%>"},
             dataType: "json",
             success: function(data){
             		
                      }
         });
        }
})





$("#set_data").bind("click",function(){
alert();
$(".test_data_class").each(function(){

  $.ajax({
             type: "GET",
             url: "/test_plan_case/set_data",
             data: {"test_plan_data[:test_case_id]":"<%=params[:test_case_id]%>","test_plan_data[:test_flow_id]": $(this).attr("test_flow_id")},
             dataType: "json",
             success: function(data){
                
                      }
         });

})



})

  </script>

app/views/test_plan_cases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Test case:</b>
  <%= @test_plan_case.test_case_id %>
</p>

<p>
  <b>Test plan:</b>
  <%= @test_plan_case.test_plan_id %>
</p>


<%= link_to 'Edit', edit_test_plan_case_path(@test_plan_case) %> |
<%= link_to 'Back', test_plan_cases_path %>