config/routes.rb
AutoTest::Application.routes.draw do
  resources :plan_types

  devise_for :users

  resources :test_plan_cases

  resources :test_plans

  resources :users

  resources :flow_date_types

  resources :flow_types

  resources :test_case_flows

  resources :test_cases 

  match 'home/index' => 'test_plan_cases#index'
  
  get '/test_plan_case/get_data' => "test_plan_cases#get_data"
  post '/test_plan_case/set_data' => "test_plan_cases#set_data"

  get '/test_cases/:id/pro' => "test_cases#pro", :as => "pro_test_cases"

  get '/test_cases/:id/excuse' => "test_cases#excuse", :as => "excuse_test_cases"

  get '/test_plans/:id/excuse' => "test_plans#excuse", :as => "excuse_test_plan"

  get '/test_plans/:id/pause' => "test_plans#pause", :as => "pause_test_plan"

  get '/test_plans/:id/stop' => "test_plans#stop", :as => "stop_test_plan"

  get '/test_plans/:id/resume' => "test_plans#resume", :as => "resume_test_plan"

  get '/test_plans/:id/result' => "test_plans#result", :as => "result_test_plan"

  get '/test_plans/:id/pro' => "test_plans#pro", :as => "pro_test_plan"

  get '/test_plans/:id/script' => "test_plans#script", :as => "script_test_plan"

  root :to => 'test_cases#index'

  

end

app/controllers/test_cases_controller.rb
class TestCasesController < ApplicationController
  check_authorization
  load_and_authorize_resource
  # GET /test_cases
  # GET /test_cases.json
  def index

    @test_cases = TestCase.where("1=1") 
    @test_cases = @test_cases.where("title like '%#{params[:title].strip}%'") if params[:title]  and params[:title] !=""
    @test_cases = @test_cases.where("user_id = #{params[:user_id]} ") if params[:user_id] and params[:user_id] !=""
    @test_cases = @test_cases.paginate :page => params[:page]||1,
                            :per_page=>10,
                            :order => 'created_at DESC'


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @test_cases }
    end
  end

  # GET /test_cases/1
  # GET /test_cases/1.json
  def show
    @test_case = TestCase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @test_case }
    end
  end

  # GET /test_cases/new
  # GET /test_cases/new.json
  def new
    @test_case = TestCase.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @test_case }
    end
  end

  # GET /test_cases/1/edit
  def edit
    @test_case = TestCase.find(params[:id])
  end

  # POST /test_cases
  # POST /test_cases.json
  def create
    @test_case = TestCase.new(params[:test_case])
    @test_case.user_id = current_user.id
    respond_to do |format|
      if @test_case.save
        format.html { redirect_to new_test_case_flow_path(:test_case_id=>@test_case.id), notice: 'Test case was successfully created.' }
        format.json { render json: @test_case, status: :created, location: @test_case }
      else
        format.html { render action: "new" }
        format.json { render json: @test_case.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /test_cases/1
  # PUT /test_cases/1.json
  def update
    @test_case = TestCase.find(params[:id])
   
    respond_to do |format|

      if @test_case.user_id.to_s == current_user.id.to_s && @test_case.update_attributes(params[:test_case])
        format.html { redirect_to @test_case, notice: 'Test case was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @test_case.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_cases/1
  # DELETE /test_cases/1.json
  def destroy
    @test_case = TestCase.find(params[:id])
    @test_case.destroy
    respond_to do |format|
      format.html { redirect_to test_cases_url }
      format.js { render :layout => false }
      format.json { head :no_content }
    end
  end



  #生成脚本
  def pro
    @test_case = TestCase.find(params[:id])
    @test_script = TestScript.new
    @test_script.test_case_id = @test_case.id
    @test_script.db_script @test_case

    @test_case = TestCase.find(params[:id])
    @test_script.file_script @test_case

      respond_to do |format|
      format.html { redirect_to test_cases_url }
      format.js { render :layout => false }
      format.json { head :no_content }
    end

  end

  def excuse
    
    @test_case = TestCase.find(params[:id])
    @test_case.test_scripts.each do |test_script|
     
       Thread.new  do  
           test_script.excuse
       end  

    end

      respond_to do |format|
      format.html { redirect_to test_cases_url }
      format.json { head :no_content }
      format.js { render :layout => false }
    end

  end


end

app/helpers/test_cases_helper.rb
module TestCasesHelper
end

app/views/test_cases/_form.html.erb
<%= form_for(@test_case) do |f| %>
  <% if @test_case.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_case.errors.count, "error") %> prohibited this test_case from being saved:</h2>

      <ul>
      <% @test_case.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :标题 %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.text_field :user_id ,:type=>'hidden'%>
  </div>
  <div class="actions">
    <%= f.submit :下一步 %>
  </div>
<% end %>

app/views/test_cases/destroy.js.erb
location.reload() 

app/views/test_cases/edit.html.erb
<h1>Editing test_case</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_case %> |
<%= link_to 'Back', test_cases_path %>

app/views/test_cases/excuse.js.erb
location.reload() 

app/views/test_cases/index.html.erb
<h1>测试用例管理</h1>

    <form action='/test_cases', method='get'>
                  
                   <div style="float:left">
                    <div style="float:left">
                      根据用户查找:
              <select id="user_id" name="user_id">
              <option value="">--请选择用户--</option>
              <%User.all.collect {|p| [ p.email, p.id ]}.each do |k,v|%>
               <option value="<%=v%>" <%= "selected" if params[:user_id] ==v.to_s %>><%=k%></option>
              <%end%>
             
              </select>

                    </div>
                    <div style="float:left">
                       根据标题查找:
                     <input type="text" name = "title" value="<%=params[:title]%>">
                     <input type="submit" class="btn btn-green big" value="提交">
                    </div>
                   </div>
  </form>
  <br>
    <br>
  <div style="float:left">
                   <%= link_to '创建用例', new_test_case_path %>
  </div>
  <br>
    <br>

<table  border="1" >
  <tr>
    <th>标题</th>
    <th>所属用户</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @test_cases.each do |test_case| %>
  <tr>
    <td><%= test_case.title %></td>
    <td><%if test_case.user %><%= test_case.user.email %><%end%></td>
    <td><%= link_to '查看用例', test_case %></td>
    
    <td><% if can? :manager, test_case %> <%= link_to '编辑', edit_test_case_path(test_case) %> <%end%></td>
    <td><%= link_to '生成脚本', pro_test_cases_path(test_case) ,:remote => true%></td>
    <td><%= link_to '执行脚本', excuse_test_cases_path(test_case) ,:remote => true%></td>
   <td> <% if can? :destroy, test_case %><%= link_to '删除用例', test_case, method: :delete, data: { confirm: 'Are you sure?' },:remote => true %><%end%></td>
  </tr>
<% end %>
</table>
  <%= will_paginate @test_cases , :params =>{:title=> params[:title],:user_id=>params[:user_id]} %>
<br />

app/views/test_cases/new.html.erb
<h1>New test_case</h1>

<%= render 'form' %>

<%= link_to 'Back', test_cases_path %>

app/views/test_cases/pro.js.erb
location.reload() 

app/views/test_cases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @test_case.title %>
</p>

<p>
  <b>Desc:</b>
  <%= @test_case.desc %>
</p>

<p>
  <b>User:</b>
  <%= @test_case.user_id %>
</p>






<div id="new_test_flow">
 <div>
    <label>步骤</label>
    <label style="margin-left:160px"> 动作类型</label>
    <label style="margin-left:60px"> 元素定位</label>
    <label style="margin-left:180px">  数据类型</label>
    <label  style="margin-left:160px"> 数据</label>
    <label  style="margin-left:160px"> 添加</label>
  </div>
   <% @test_case.test_case_flows.each do |test_case_flow| %>
 <div id="div_<%=test_case_flow.flow_seq%>" >
    <%= form_for(test_case_flow, :remote => true) do |f| %>
    <%= f.text_field :test_case_id,:type=>'hidden' %>
    <%= f.number_field :flow_seq,:readonly=>'readonly' %>
    <%= f.select :flow_type_id, FlowType.find(:all).collect {|p| [ p.name, p.id ] } %>
    <%= f.text_field :flow_location,:id=>"test_case_flow_flow_location_#{test_case_flow.id}" ,:style=>"width:350px"%>
    <%= f.select :flow_date_type_id, FlowDateType.find(:all).collect {|p| [ p.name, p.id ] } %>
    <%= f.text_area :flow_date,:rows=>1,:style=>"margin-top:6px;margin-bottom:-6px" %>
    <%if current_user.id.to_s == @test_case.user_id.to_s%><%= f.submit :保存并新增 %><%end%>
    <%if current_user.id.to_s == @test_case.user_id.to_s%><%= f.submit :保存并插入 %><%end%>
    <%if current_user.id.to_s == @test_case.user_id.to_s%><%= f.submit :保存 %><%end%>
    <%if current_user.id.to_s == @test_case.user_id.to_s%><%= link_to '删除本行', test_case_flow, method: :delete, data: { confirm: '确定删除' },:remote => true %><%end%>
    <% end %>
 </div>
  <% end %>
  </div>
<%= link_to 'Back', test_cases_path %>