config/routes.rb
AutoTest::Application.routes.draw do
  resources :plan_types

  devise_for :users

  resources :test_plan_cases

  resources :test_plans

  resources :users

  resources :flow_date_types

  resources :flow_types

  resources :test_case_flows

  resources :test_cases 

  match 'home/index' => 'test_plan_cases#index'
  
  get '/test_plan_case/get_data' => "test_plan_cases#get_data"
  post '/test_plan_case/set_data' => "test_plan_cases#set_data"

  get '/test_cases/:id/pro' => "test_cases#pro", :as => "pro_test_cases"

  get '/test_cases/:id/excuse' => "test_cases#excuse", :as => "excuse_test_cases"

  get '/test_plans/:id/excuse' => "test_plans#excuse", :as => "excuse_test_plan"

  get '/test_plans/:id/pause' => "test_plans#pause", :as => "pause_test_plan"

  get '/test_plans/:id/stop' => "test_plans#stop", :as => "stop_test_plan"

  get '/test_plans/:id/resume' => "test_plans#resume", :as => "resume_test_plan"

  get '/test_plans/:id/result' => "test_plans#result", :as => "result_test_plan"

  get '/test_plans/:id/pro' => "test_plans#pro", :as => "pro_test_plan"

  get '/test_plans/:id/script' => "test_plans#script", :as => "script_test_plan"

  root :to => 'test_cases#index'

  

end

app/models/test_plan.rb
# encoding: utf-8
require 'fileutils'
class TestPlan < ActiveRecord::Base
	attr_accessible :plan_type_id,:host, :user_name,:log_path, :name, :pd,:test_num,:user_id,:memo,:time_after,:time_every,:time_at,:time_cron,:job_id,:job_sstatus,:carbon_email

   attr_accessor :time_select
   	has_many :test_plan_cases, :dependent => :destroy
   	has_many :test_cases , :through=>:test_plan_cases
   	has_many :test_scripts, :dependent => :destroy
   	has_many :test_plan_datas, :dependent => :destroy
    has_many :test_results, :dependent => :destroy
    belongs_to :user
    belongs_to :plan_type    

   	
    def time_select

      if time_cron != nil and time_cron !=''
        return 1
      end

      if time_at != nil and time_at !=''
        return 2
      end

      if time_after != nil and time_after !=''
        return 3
      end

      if time_every != nil and time_every !=''
        return 4
      end
      return 0

    end

    def file_script
   		path = "./test_script/" + self.id.to_s 
   		control_file_path = path + "/" + self.id.to_s + "_control.rb"
   		if  File.exist? path
   			FileUtils.rm_rf path	
   		end
		Dir.mkdir(path)
   		
		control_file = File.new(control_file_path,"w")

   		self.test_scripts.each do |test_script|
   			name = path + '/' + test_script.test_plan_id.to_s + "_" + test_script.test_case_id.to_s + 
  				 test_script.id.to_s +  ".rb" 
  			scriptFile = File.new(name,"w")
  			scriptFile.write test_script.script_content 

        control_file.write "begin \r\n"
  			control_file.write "load \'" + name + "\'\r\n"

        control_file.write "testResult = TestResult.setResult(:test_script_id=>" + test_script.id.to_s + ",:test_plan_id=>" + test_script.test_plan_id.to_s + ",:test_case_id=>" + test_script.test_case_id.to_s  + ",:test_result_flag => true) \r\n"

        control_file.write "rescue Exception => e \r\n"
        control_file.write "testResult = TestResult.setResult(:test_script_id=>" + test_script.id.to_s + ",:test_plan_id=>" + test_script.test_plan_id.to_s + ",:test_case_id=>" + test_script.test_case_id.to_s  + ",:test_result_content=>e.message,:test_result_flag => false) \r\n"
        control_file.write "end \r\n"

   			scriptFile.close
  		end
  		control_file.close
   	end


   	def excuse
      begin 
		load "./test_script/" + self.id.to_s + "/" + self.id.to_s + "_control.rb"
    temp_test_plan = TestPlan.find(self.id)
    flag =  1
    temp_test_plan.test_results.each do |test_result|
      puts "用例执行结果：" + test_result.test_result_flag.to_s
      if !test_result.test_result_flag
        flag =0
        break
      end
    end

    puts "======================================================================================="
    puts '执行结果为：'  + flag.to_s
      for i in 0..2
        if flag == 0 
            if i == 2
              break
            end
            #TestResult.delete_all("test_plan_id = #{self.id}")
            load "./test_script/" + self.id.to_s + "/" + self.id.to_s + "_control.rb"
            temp_test_plan = TestPlan.find(self.id)
           temp_test_plan.test_results.each do |test_result|
            if test_result.test_result_flag == 0
              flag =0
              break
            end
          end
        else
          break
      end
    end

    ResultMailer.send_mail(self.user.email,self.id).deliver

    carbon_email.split("|").each do |email|
      ResultMailer.send_mail(email,self.id).deliver
    end
    rescue Exception => e 

    puts e
    end 

    
   	end

    def get_error_cast_num
     return  TestResult.where("test_plan_id = ? and test_result_flag = ? ",id,false).length
    end



    def get_job_status
     
      job = $scheduler.job(self.job_id)

      if job == nil
        if self.job_status !='停止'
            self.job_status = '停止'
            self.save
          end
        return "停止" 
      end

      if job.scheduled?

          if time_select == 4 
           if job.paused?
            if self.job_status !='暂停中'
              self.job_status = '暂停中'
              self.save
            end
          return "暂停中"
          end
          end

          if self.job_status !='运行中'
            self.job_status = '运行中'
            self.save
          end
          return "运行中"
      end
    
    end

end

app/controllers/test_plans_controller.rb
# encoding: utf-8
class TestPlansController < ApplicationController
 
  # GET /test_plans
  # GET /test_plans.json
  def index

    @test_plans = TestPlan.where("1=1") 
    @test_plans = @test_plans.where("name like '%#{params[:title].strip}%'") if params[:title]  and params[:title] !=""
    @test_plans = @test_plans.where("user_id = #{params[:user_id]} ") if params[:user_id] and params[:user_id] !=""
     @test_plans = @test_plans.where("plan_type_id = #{params[:plan_type_id]} ") if params[:plan_type_id] and params[:plan_type_id] !=""
    @test_plans = @test_plans.paginate :page => params[:page]||1,
                            :per_page=>10,
                            :order => 'created_at DESC'
  
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @test_plans }
    end

  end

  # GET /test_plans/1
  # GET /test_plans/1.json
  def show
    @test_plan = TestPlan.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @test_plan }
    end
  end

  # GET /test_plans/new
  # GET /test_plans/new.json
  def new
    @test_plan = TestPlan.new

    

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @test_plan }
    end
  end

  # GET /test_plans/1/edit
  def edit
    @test_plan = TestPlan.find(params[:id])
   
  end


  def clean_test_plan test_plan
    test_plan.time_at = ''
    test_plan.time_cron = ''
    test_plan.time_every = ''
    test_plan.time_after = ''
    return test_plan
  end


def clean_param params
     params[:test_plan][:time_at] = '' 
     params[:test_plan][:time_cron] ='' 
     params[:test_plan][:time_every] = '' 
     params[:test_plan][:time_after] = '' 
  end


  # POST /test_plans
  # POST /test_plans.json
  def create
    

    time_select = params[:test_plan][:time_select]
    params[:test_plan].delete(:time_select) 

    @test_plan = TestPlan.new(params[:test_plan])
   
    if time_select =='1'
       @test_plan = clean_test_plan @test_plan
       @test_plan.time_cron = params[:test_plan][:time_cron]
    end

    if time_select =='2'
    d = Date.civil(params[:time_at][:year].to_i, params[:time_at][:month].to_i, params[:time_at][:day].to_i)

    @test_plan = clean_test_plan @test_plan
    @test_plan.time_at = d.strftime("%Y/%m/%d %H:%M:%S")
    end

    if time_select =='3'
       @test_plan = clean_test_plan @test_plan
       @test_plan.time_after = params[:test_plan][:time_after]
    end

    if time_select =='4'
       @test_plan = clean_test_plan @test_plan
       @test_plan.time_every = params[:test_plan][:time_every]
    end



    @test_plan.user_id = current_user.id
    respond_to do |format|
      if @test_plan.save
        format.html { redirect_to new_test_plan_case_path(:test_plan_id=>@test_plan.id), notice: 'Test case was successfully created.' }
        format.json { render json: @test_plan, status: :created, location: @test_plan }
      else
        format.html { render action: "new" }
        format.json { render json: @test_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /test_plans/1
  # PUT /test_plans/1.json
  def update
    @test_plan = TestPlan.find(params[:id])
   
    time_select = params[:test_plan][:time_select]
    params[:test_plan].delete(:time_select) 

   

    if time_select =='1'
       @test_plan.time_cron = params[:test_plan][:time_cron]
       clean_param params
       params[:test_plan][:time_cron] = @test_plan.time_cron
    end

    if time_select =='2'
    d = Time.local(params[:time_at][:year].to_i, params[:time_at][:month].to_i, params[:time_at][:day].to_i, params[:time_at][:hour].to_i, params[:time_at][:minute].to_i,0)   
 

    clean_param params
    @test_plan.time_at = d.strftime("%Y/%m/%d %H:%M:%S")
    puts '==========================================================='

    params[:test_plan][:time_at] = @test_plan.time_at

     puts '===========================================================' +  params[:test_plan][:time_at]

    end

    if time_select =='3'
       @test_plan.time_after = params[:test_plan][:time_after]
       clean_param params
       params[:test_plan][:time_after] = @test_plan.time_after

    end

    if time_select =='4'

       @test_plan.time_every = params[:test_plan][:time_every]
       clean_param params
       params[:test_plan][:time_every] = @test_plan.time_every
    end

    @test_plan.user_id = current_user.id


    puts "----------------------------------------------------------------------------------------------"
    puts params[:test_plan]

    respond_to do |format|
      if @test_plan.user_id == current_user.id && @test_plan.update_attributes(params[:test_plan])
        format.html { redirect_to new_test_plan_case_path(:test_plan_id=>@test_plan.id), notice: 'Test case was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @test_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_plans/1
  # DELETE /test_plans/1.json
  def destroy
    @test_plan = TestPlan.find(params[:id])
   
    @test_plan.destroy

    respond_to do |format|
      format.html { redirect_to test_plans_url }
       format.js { render :layout => false }
      format.json { head :no_content }
    end
  end

  def excuse
    @test_plan = TestPlan.find(params[:id])
    
     TestResult.delete_all("test_plan_id = #{@test_plan.id}")

     Thread.new  do  
     
     
      job_id = ""


    if @test_plan.time_after != nil  and @test_plan.time_after != ''
      after_sec = @test_plan.time_after
      job_id = $scheduler.in after_sec.to_s do
        @test_plan.excuse
      end 
     end

     if @test_plan.time_at != nil  and @test_plan.time_at != ''
      time_at = @test_plan.time_at
      job_id = $scheduler.at time_at.to_s do
        @test_plan.excuse
      end 
     end


     if @test_plan.time_cron != nil  and @test_plan.time_cron != ''
      time_cron = @test_plan.time_cron
      job_id = $scheduler.cron time_cron.to_s do
        @test_plan.excuse
      end 
     end


     if @test_plan.time_every != nil and @test_plan.time_every != '' 
      every_sec = @test_plan.time_every.to_i * 60

      job_id = $scheduler.every every_sec.to_s do
        @test_plan.excuse
      end 
     end

     
     if job_id != ''
      puts job_id
      @test_plan.job_id =  job_id
      @test_plan.job_status = '运行中'
      @test_plan.save
      $scheduler.join
    end
     
     if(@test_plan.time_select == 0)
      @test_plan.excuse

     end

      


      
      end
    
     respond_to do |format|
      format.html { redirect_to test_plans_url }
       format.js { render :layout => false }
      format.json { head :no_content }
    end
  end



  def pause
    @test_plan = TestPlan.find(params[:id])

    

    job = $scheduler.job(@test_plan.job_id)
    if job !=nil
    puts job 
    puts "-======================================================================================================================" 
    puts job.paused? 
    job.pause
     puts job.paused? 
     puts "-======================================================================================================================" 
    end
     respond_to do |format|
      format.html { redirect_to test_plans_url }
       format.js { render :layout => false }
      format.json { head :no_content }
    end
  end


def resume
    @test_plan = TestPlan.find(params[:id])
    
    job = $scheduler.job(@test_plan.job_id)
    if job !=nil
    job = $scheduler.job(@test_plan.job_id)
    puts job 
    job.resume
    end
    
     respond_to do |format|
      format.html { redirect_to test_plans_url }
       format.js { render :layout => false }
      format.json { head :no_content }
    end
  end


  def stop
    @test_plan = TestPlan.find(params[:id])
  
    job = $scheduler.job(@test_plan.job_id)
    if job !=nil
     $scheduler.unschedule(@test_plan.job_id)
   end
    
     respond_to do |format|
      format.html { redirect_to test_plans_url }
       format.js { render :layout => false }
      format.json { head :no_content }
    end
  end




  def pro
      @test_plan = TestPlan.find(params[:id])
      authorize! :done, @test_plan
      testScript = TestScript.new 

      testScript.db_plan_script(@test_plan)

      @test_plan.file_script

      respond_to do |format|
      format.html { redirect_to test_plans_url }
       format.js { render :layout => false }
      format.json { head :no_content }
    end

  end


  def result

  @test_plan = TestPlan.find(params[:id])

  @test_results = @test_plan.test_results

  end


  def script
    
    @testScript = TestScript.find(params[:id])
    authorize! :read, @testScript
  end


end

app/helpers/test_plans_helper.rb
module TestPlansHelper
end

app/views/test_plans/_form.html.erb
<%= form_for(@test_plan) do |f| %>
  <% if @test_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_plan.errors.count, "error") %> prohibited this test_plan from being saved:</h2>

      <ul>
      <% @test_plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :类型 %><br />
    <%= f.select :plan_type_id, PlanType.find(:all).collect {|p| [ p.name, p.id ] } %>
  </div>

  <div class="field">
    <%= f.label :名称 %><br />
    <%= f.text_field :name %>
  </div>

    <div class="field">
    <%= f.label :"抄送邮件(用 | 分割)" %><br />
    <%= f.text_field :carbon_email %>
  </div>

  <p>----------------------------------------------------------------------------</p>
        <div class="field">
    <%= f.label :cron—时间定义%><br />
    指定时间：<%= f.radio_button(:time_select, "1",:onclick=>"$('.time_select').hide();$('#time_cron').show()") %> <br>
    <div id="time_cron" <%if @test_plan.time_select !=1 %>style="display:none" <%end%> class="time_select">
    <%= f.text_field :time_cron %>

    <p>1. Seconds 秒 
2. Minutes 分钟 
3. Hours 小时 
4. Day-of-Month 月中的天 
5. Month 月 
6. Day-of-Week 周中的天 
7. Year (optional field) 年（可选的域）
</p>
</div>
   </div>


 <p>----------------------------------------------------------------------------</p>
    <div class="field">
    <%= f.label :在什么时候执行%><br />
    指定时间：<%= f.radio_button(:time_select, "2",:onclick=>"$('.time_select').hide();$('#time_at').show()") %> <br>
    <div id="time_at" class="time_select" <%if @test_plan.time_select !=2 %>style="display:none" <%end%>>
    <%= select_datetime  Date.today, prefix: :time_at %>
    </div>
   </div>
 <p>----------------------------------------------------------------------------</p>
  <div class="field">
    <%= f.label :几秒后执行 %><br />
    指定时间：<%= f.radio_button(:time_select, 3,:onclick=>"$('.time_select').hide();$('#time_after').show()") %> <br>
    <div id="time_after" class="time_select" <%if @test_plan.time_select !=3 %>style="display:none" <%end%>>
    <%= f.select :time_after,  [['请选择', ''],['10s', 10],['30s', 30],['60s', 60],['120s', 120],['300s', 300]]%>
  </div>
  </div>
 <p>----------------------------------------------------------------------------</p>

  <div class="field">
    <%= f.label :每隔几分钟执行 %><br />
    指定时间：<%= f.radio_button(:time_select, "4",:onclick=>"$('.time_select').hide();$('#time_every').show()") %> <br>
    <div id="time_every" class="time_select" <%if @test_plan.time_select !=4 %>style="display:none" <%end%>>
    <%= f.select :time_every,  [['请选择', ''],['5分钟', 5],['10分钟', 10],['20分钟', 30],['30分钟', 30],['60分钟', 60],['120分钟', 120]]%>
  </div>
  </div>
 <p>----------------------------------------------------------------------------</p>



  <div class="field">
    <%= f.label :服务器ip（用于获取短信和密码，可不填） %><br />
    <%= f.text_field :host %>
  </div>
  <div class="field">
    <%= f.label :用户名 %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :密码 %><br />
    <%= f.text_field :pd %>
  </div>
  <div class="field">
    <%= f.label :log日志路径 %><br />
    <%= f.text_field :log_path %>
  </div>
   <div class="field">
    <%= f.label :备注 %><br />
    <%= f.text_area :memo %>
  </div>
  <div class="actions">
    <%= f.submit :value=>"下一步，选择测试用例"%>
  </div>
<% end %>

app/views/test_plans/destroy.js.erb
location.reload() 

app/views/test_plans/edit.html.erb
<h1>Editing test_plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_plan %> |
<%= link_to 'Back', test_plans_path %>

app/views/test_plans/excuse.js.erb
location.reload() 

app/views/test_plans/index.html.erb
<h1>测试计划</h1>
    <form action='/test_plans', method='get'>
                  
                   <div style="float:left">
                    <div style="float:left">
                      根据用户查找:
              <select id="user_id" name="user_id">
              <option value="">--请选择用户--</option>
              <%User.all.collect {|p| [ p.email, p.id ]}.each do |k,v|%>
               <option value="<%=v%>" <%= "selected" if params[:user_id] ==v.to_s %>><%=k%></option>
              <%end%>
             
              </select>

                    </div>
                    <div style="float:left">
                       根据标题查找:
                     <input type="text" name = "title" value="<%=params[:title]%>">
                    
                    </div>

                                        <div style="float:left">
                       根据类型查找:
                     <select id="plan_type_id" name="plan_type_id">
              <option value="">--请选择类型--</option>
              <%PlanType.all.collect {|p| [ p.name, p.id ]}.each do |k,v|%>
               <option value="<%=v%>" <%= "selected" if params[:plan_type_id] ==v.to_s %>><%=k%></option>
              <%end%>
              </select>
               <input type="submit" class="btn btn-green big" value="提交">
                    </div>

                   </div>
  </form>
  <br>
    <br>
  <div style="float:left">
                   <%= link_to '创建计划', new_test_plan_path %>
  </div>
  <br>
    <br>
<table  border="1" >
  <tr>
    <th>类型</th>
    <th>名称</th>
    <th>所属人</th>
    <th>用例数(测试用例数X数据)</th>
    <th>最近一次执行脚本的错误用例数</th>
     <th>计划状态</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @test_plans.each do |test_plan| %>
  <tr>
     <td><%= test_plan.plan_type ? test_plan.plan_type.name : "" %></td>
    <td><%= test_plan.name %></td>
    <td><%if test_plan.user %><%= test_plan.user.email %><%end%></td>
    <td><%= test_plan.test_num %></td>
    <td><%= test_plan.get_error_cast_num %></td>
     <td><%= test_plan.get_job_status() %></td>
    <td><%if "#{current_user.id }"== "#{test_plan.user_id}"%><%= link_to '查看', test_plan %><%end%></td>
    <td><%if "#{current_user.id }"== "#{test_plan.user_id}"%><%= link_to '编辑', edit_test_plan_path(test_plan) %><%end%></td>
    <td><% if can? :done, test_plan %>  <%= link_to '生成所有脚本', pro_test_plan_path(test_plan) ,:remote => true%><%end%></td>
    <td>
        <%if test_plan.get_job_status()  == "停止"%>
            <% if can? :done, test_plan %> 
        <%= link_to '启动', excuse_test_plan_path(test_plan) ,:remote => true%>
           <%end%>
        <%end%>
    </td>
     <td>
        <%if test_plan.get_job_status()  == "运行中" || test_plan.get_job_status()  == "暂停中"%>
           <% if can? :done, test_plan %> 
        <%= link_to '停止', stop_test_plan_path(test_plan) ,:remote => true%>
           <%end%>
        <%end%>
    </td>
     <td>
        <%if test_plan.get_job_status()  == "运行中"%>
            <% if can? :done, test_plan %> 
        <%= link_to '暂停', pause_test_plan_path(test_plan) ,:remote => true%>
           <%end%>
        <%end%>
    </td>
     <td>
        <%if test_plan.get_job_status()  == "暂停中"%>
           <% if can? :done, test_plan %> 
        <%= link_to '恢复', resume_test_plan_path(test_plan) ,:remote => true%>
           <%end%>
        <%end%>
    </td>
    <td><%= link_to '查看最近一次运行结果', result_test_plan_path(test_plan),:target=>"_blank" %></td>
    <td><%if "#{current_user.id }"== "#{test_plan.user_id}"%><%= link_to '删除', test_plan, method: :delete, data: { confirm: 'Are you sure?' } ,:remote => true%><%end%></td>
  </tr>
<% end %>
</table>
 <%= will_paginate @test_plans , :params =>{:title=> params[:title],:user_id=>params[:user_id]} %>
<br />

app/views/test_plans/new.html.erb
<h1>新增测试计划</h1>

<%= render 'form' %>

<%= link_to 'Back', test_plans_path %>

app/views/test_plans/pause.js.erb
location.reload() 

app/views/test_plans/pro.js.erb
location.reload() 

app/views/test_plans/result.html.erb
<h1>测试结果</h1>

<table border="1">
  <tr>
    <th>测试计划</th>
    <th>测试用例</th>
    <th>是否成功</th>
    <th>错误描述</th>
    <th>查看脚本</th>
  </tr>

<% @test_results.each do |test_result| %>
  <tr>
    <td><%= test_result.test_plan.name %></td>
    <td><%= test_result.test_case.title %></td>
    <td><%if test_result.test_result_flag%> 通过 <%else%> 不通过<%end%></td>
    <td><%if test_result.test_result_content %><%= test_result.test_result_content.html_safe %><%end%></td>
    <td><%if "#{current_user.id }"== "#{test_result.test_plan.user_id}"%><%= link_to '查看脚本', script_test_plan_path(:id=>test_result.test_script_id) ,:target=>"_blank" %><%end%></td>
  </tr>
<% end %>
</table>

<br />

app/views/test_plans/resume.js.erb
location.reload() 

app/views/test_plans/script.html.erb
<%= coderay(@testScript.script_content).html_safe %> 

app/views/test_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>类型:</b>
  <%= @test_plan.plan_type.name ? @test_plan.plan_type.name : ""%>
</p>

<p>
  <b>名称:</b>
  <%= @test_plan.name %>
</p>

<p>
  <b>几秒后执行:</b>
  <%= @test_plan.time_after %>
</p>

<p>
  <b>几分钟执行一次:</b>
  <%= @test_plan.time_every %>
</p>

<p>
  <b>什么时候开始执行:</b>
  <%= @test_plan.time_at %>
</p>

<p>
  <b>cron时间设置:</b>
  <%= @test_plan.time_cron %>
</p>

<p>
  <b>Pd:</b>
  <%= @test_plan.pd %>
</p>

<p>
  <b>Log path:</b>
  <%= @test_plan.log_path %>
</p>

<p>
  <b>memo:</b>
  <%= @test_plan.memo %>
</p>


<%= link_to 'Edit', edit_test_plan_path(@test_plan) %> |
<%= link_to 'Back', test_plans_path %>

app/views/test_plans/stop.js.erb
location.reload() 