config/routes.rb
AutoTest::Application.routes.draw do
  resources :plan_types

  devise_for :users

  resources :test_plan_cases

  resources :test_plans

  resources :users

  resources :flow_date_types

  resources :flow_types

  resources :test_case_flows

  resources :test_cases 

  match 'home/index' => 'test_plan_cases#index'
  
  get '/test_plan_case/get_data' => "test_plan_cases#get_data"
  post '/test_plan_case/set_data' => "test_plan_cases#set_data"

  get '/test_cases/:id/pro' => "test_cases#pro", :as => "pro_test_cases"

  get '/test_cases/:id/excuse' => "test_cases#excuse", :as => "excuse_test_cases"

  get '/test_plans/:id/excuse' => "test_plans#excuse", :as => "excuse_test_plan"

  get '/test_plans/:id/pause' => "test_plans#pause", :as => "pause_test_plan"

  get '/test_plans/:id/stop' => "test_plans#stop", :as => "stop_test_plan"

  get '/test_plans/:id/resume' => "test_plans#resume", :as => "resume_test_plan"

  get '/test_plans/:id/result' => "test_plans#result", :as => "result_test_plan"

  get '/test_plans/:id/pro' => "test_plans#pro", :as => "pro_test_plan"

  get '/test_plans/:id/script' => "test_plans#script", :as => "script_test_plan"

  root :to => 'test_cases#index'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AutoTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%if current_user%>
<p>欢迎你， <%=current_user.email%> <%= link_to '退出', destroy_user_session_path, :method=>'delete' %></p>
<%end%>
<%= link_to '测试用例管理', test_cases_path %>



<%= link_to '测试计划管理', test_plans_path %>

<%= link_to '计划类型管理', plan_types_path %>
<% if can? :manage, FlowType %> <%= link_to '动作类型管理', flow_types_path %> <%end%>

<% if can? :manage, FlowDateType %> <%= link_to '数据类型管理', flow_date_types_path %><%end%>

<% if can? :manage, User %> <%= link_to '用户管理', users_path %><%end%>

<%= link_to '下载chrome插件', "/chrome_auto_test.rar",:title=>"下载插件后解压，然后chrome浏览器加载插件" %>


<%= yield %>

</body>
</html>